#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 131
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 37
#define ALIAS_COUNT 0
#define TOKEN_COUNT 23
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 20
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  sym_identifier = 1,
  sym__newline = 2,
  anon_sym_DQUOTE = 3,
  aux_sym_string_token1 = 4,
  anon_sym_SQUOTE = 5,
  aux_sym_string_token2 = 6,
  sym_integer = 7,
  sym__ws = 8,
  anon_sym_LPAREN = 9,
  anon_sym_COMMA = 10,
  anon_sym_RPAREN = 11,
  anon_sym_LBRACE_LBRACE = 12,
  anon_sym_RBRACE_RBRACE = 13,
  anon_sym_LBRACE_PERCENT = 14,
  anon_sym_join = 15,
  anon_sym_in = 16,
  anon_sym_with = 17,
  anon_sym_PERCENT_RBRACE = 18,
  anon_sym_endjoin = 19,
  anon_sym_for = 20,
  anon_sym_endfor = 21,
  sym_text_statement = 22,
  sym_source_file = 23,
  sym_string = 24,
  sym_reference_expression = 25,
  sym_literal_expression = 26,
  sym__pattern = 27,
  sym__statement = 28,
  sym__expression = 29,
  sym_var_pattern = 30,
  sym_tuple_pattern = 31,
  sym_expression_statement = 32,
  sym_join_statement = 33,
  sym_for_in_statement = 34,
  aux_sym_source_file_repeat1 = 35,
  aux_sym_tuple_pattern_repeat1 = 36,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym__newline] = "_newline",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token1] = "string_token1",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_string_token2] = "string_token2",
  [sym_integer] = "integer",
  [sym__ws] = "_ws",
  [anon_sym_LPAREN] = "(",
  [anon_sym_COMMA] = ",",
  [anon_sym_RPAREN] = ")",
  [anon_sym_LBRACE_LBRACE] = "{{",
  [anon_sym_RBRACE_RBRACE] = "}}",
  [anon_sym_LBRACE_PERCENT] = "{%",
  [anon_sym_join] = "join",
  [anon_sym_in] = "in",
  [anon_sym_with] = "with",
  [anon_sym_PERCENT_RBRACE] = "%}",
  [anon_sym_endjoin] = "endjoin",
  [anon_sym_for] = "for",
  [anon_sym_endfor] = "endfor",
  [sym_text_statement] = "text_statement",
  [sym_source_file] = "source_file",
  [sym_string] = "string",
  [sym_reference_expression] = "reference_expression",
  [sym_literal_expression] = "literal_expression",
  [sym__pattern] = "_pattern",
  [sym__statement] = "_statement",
  [sym__expression] = "_expression",
  [sym_var_pattern] = "var_pattern",
  [sym_tuple_pattern] = "tuple_pattern",
  [sym_expression_statement] = "expression_statement",
  [sym_join_statement] = "join_statement",
  [sym_for_in_statement] = "for_in_statement",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_tuple_pattern_repeat1] = "tuple_pattern_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym__newline] = sym__newline,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_string_token2] = aux_sym_string_token2,
  [sym_integer] = sym_integer,
  [sym__ws] = sym__ws,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_COMMA] = anon_sym_COMMA,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_LBRACE_LBRACE] = anon_sym_LBRACE_LBRACE,
  [anon_sym_RBRACE_RBRACE] = anon_sym_RBRACE_RBRACE,
  [anon_sym_LBRACE_PERCENT] = anon_sym_LBRACE_PERCENT,
  [anon_sym_join] = anon_sym_join,
  [anon_sym_in] = anon_sym_in,
  [anon_sym_with] = anon_sym_with,
  [anon_sym_PERCENT_RBRACE] = anon_sym_PERCENT_RBRACE,
  [anon_sym_endjoin] = anon_sym_endjoin,
  [anon_sym_for] = anon_sym_for,
  [anon_sym_endfor] = anon_sym_endfor,
  [sym_text_statement] = sym_text_statement,
  [sym_source_file] = sym_source_file,
  [sym_string] = sym_string,
  [sym_reference_expression] = sym_reference_expression,
  [sym_literal_expression] = sym_literal_expression,
  [sym__pattern] = sym__pattern,
  [sym__statement] = sym__statement,
  [sym__expression] = sym__expression,
  [sym_var_pattern] = sym_var_pattern,
  [sym_tuple_pattern] = sym_tuple_pattern,
  [sym_expression_statement] = sym_expression_statement,
  [sym_join_statement] = sym_join_statement,
  [sym_for_in_statement] = sym_for_in_statement,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_tuple_pattern_repeat1] = aux_sym_tuple_pattern_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_integer] = {
    .visible = true,
    .named = true,
  },
  [sym__ws] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COMMA] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_join] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_in] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_with] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_endjoin] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_for] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_endfor] = {
    .visible = true,
    .named = false,
  },
  [sym_text_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_reference_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_literal_expression] = {
    .visible = true,
    .named = true,
  },
  [sym__pattern] = {
    .visible = false,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym__expression] = {
    .visible = false,
    .named = true,
  },
  [sym_var_pattern] = {
    .visible = true,
    .named = true,
  },
  [sym_tuple_pattern] = {
    .visible = true,
    .named = true,
  },
  [sym_expression_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_join_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_for_in_statement] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_tuple_pattern_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 6,
  [8] = 5,
  [9] = 9,
  [10] = 10,
  [11] = 10,
  [12] = 12,
  [13] = 9,
  [14] = 14,
  [15] = 12,
  [16] = 16,
  [17] = 4,
  [18] = 14,
  [19] = 16,
  [20] = 3,
  [21] = 21,
  [22] = 21,
  [23] = 23,
  [24] = 24,
  [25] = 23,
  [26] = 24,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 28,
  [36] = 32,
  [37] = 37,
  [38] = 31,
  [39] = 39,
  [40] = 40,
  [41] = 39,
  [42] = 42,
  [43] = 43,
  [44] = 33,
  [45] = 40,
  [46] = 29,
  [47] = 43,
  [48] = 30,
  [49] = 37,
  [50] = 34,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 56,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 62,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 57,
  [79] = 79,
  [80] = 80,
  [81] = 54,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 87,
  [88] = 61,
  [89] = 68,
  [90] = 71,
  [91] = 53,
  [92] = 92,
  [93] = 86,
  [94] = 70,
  [95] = 63,
  [96] = 87,
  [97] = 69,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 74,
  [103] = 72,
  [104] = 67,
  [105] = 64,
  [106] = 92,
  [107] = 52,
  [108] = 108,
  [109] = 109,
  [110] = 76,
  [111] = 73,
  [112] = 79,
  [113] = 75,
  [114] = 114,
  [115] = 115,
  [116] = 84,
  [117] = 77,
  [118] = 98,
  [119] = 80,
  [120] = 100,
  [121] = 83,
  [122] = 122,
  [123] = 85,
  [124] = 108,
  [125] = 99,
  [126] = 126,
  [127] = 101,
  [128] = 66,
  [129] = 129,
  [130] = 109,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ACCEPT_TOKEN(sym__ws);
      if (eof) ADVANCE(6);
      if (lookahead == '\n') ADVANCE(7);
      if (lookahead == '{') ADVANCE(2);
      if (lookahead == '}') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(15);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(8);
      if (lookahead == '%') ADVANCE(4);
      if (lookahead == '\'') ADVANCE(10);
      if (lookahead == '(') ADVANCE(16);
      if (lookahead == ')') ADVANCE(18);
      if (lookahead == ',') ADVANCE(17);
      if (lookahead == '}') ADVANCE(3);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(12);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 2:
      if (lookahead == '%') ADVANCE(21);
      if (lookahead == '{') ADVANCE(19);
      END_STATE();
    case 3:
      if (lookahead == '}') ADVANCE(20);
      END_STATE();
    case 4:
      if (lookahead == '}') ADVANCE(22);
      END_STATE();
    case 5:
      if (eof) ADVANCE(6);
      if (lookahead == '{') ADVANCE(23);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 6:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(sym__newline);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(15);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(9);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(11);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_integer);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym__ws);
      if (lookahead == '}') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(15);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym__ws);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_COMMA);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(anon_sym_RBRACE_RBRACE);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_LBRACE_PERCENT);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(anon_sym_PERCENT_RBRACE);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_text_statement);
      if (lookahead == '%') ADVANCE(21);
      if (lookahead == '{') ADVANCE(19);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_text_statement);
      if (lookahead != 0 &&
          lookahead != '{') ADVANCE(24);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'e') ADVANCE(1);
      if (lookahead == 'f') ADVANCE(2);
      if (lookahead == 'i') ADVANCE(3);
      if (lookahead == 'j') ADVANCE(4);
      if (lookahead == 'w') ADVANCE(5);
      END_STATE();
    case 1:
      if (lookahead == 'n') ADVANCE(6);
      END_STATE();
    case 2:
      if (lookahead == 'o') ADVANCE(7);
      END_STATE();
    case 3:
      if (lookahead == 'n') ADVANCE(8);
      END_STATE();
    case 4:
      if (lookahead == 'o') ADVANCE(9);
      END_STATE();
    case 5:
      if (lookahead == 'i') ADVANCE(10);
      END_STATE();
    case 6:
      if (lookahead == 'd') ADVANCE(11);
      END_STATE();
    case 7:
      if (lookahead == 'r') ADVANCE(12);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(anon_sym_in);
      END_STATE();
    case 9:
      if (lookahead == 'i') ADVANCE(13);
      END_STATE();
    case 10:
      if (lookahead == 't') ADVANCE(14);
      END_STATE();
    case 11:
      if (lookahead == 'f') ADVANCE(15);
      if (lookahead == 'j') ADVANCE(16);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_for);
      END_STATE();
    case 13:
      if (lookahead == 'n') ADVANCE(17);
      END_STATE();
    case 14:
      if (lookahead == 'h') ADVANCE(18);
      END_STATE();
    case 15:
      if (lookahead == 'o') ADVANCE(19);
      END_STATE();
    case 16:
      if (lookahead == 'o') ADVANCE(20);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_join);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_with);
      END_STATE();
    case 19:
      if (lookahead == 'r') ADVANCE(21);
      END_STATE();
    case 20:
      if (lookahead == 'i') ADVANCE(22);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(anon_sym_endfor);
      END_STATE();
    case 22:
      if (lookahead == 'n') ADVANCE(23);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_endjoin);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 5},
  [2] = {.lex_state = 5},
  [3] = {.lex_state = 5},
  [4] = {.lex_state = 5},
  [5] = {.lex_state = 1},
  [6] = {.lex_state = 1},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 5},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 5},
  [14] = {.lex_state = 5},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 5},
  [17] = {.lex_state = 5},
  [18] = {.lex_state = 5},
  [19] = {.lex_state = 5},
  [20] = {.lex_state = 5},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 5},
  [29] = {.lex_state = 5},
  [30] = {.lex_state = 5},
  [31] = {.lex_state = 5},
  [32] = {.lex_state = 5},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 5},
  [36] = {.lex_state = 5},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 5},
  [39] = {.lex_state = 1},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 5},
  [47] = {.lex_state = 1},
  [48] = {.lex_state = 5},
  [49] = {.lex_state = 1},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 1},
  [53] = {.lex_state = 1},
  [54] = {.lex_state = 1},
  [55] = {.lex_state = 14},
  [56] = {.lex_state = 1},
  [57] = {.lex_state = 1},
  [58] = {.lex_state = 1},
  [59] = {.lex_state = 14},
  [60] = {.lex_state = 14},
  [61] = {.lex_state = 1},
  [62] = {.lex_state = 15},
  [63] = {.lex_state = 15},
  [64] = {.lex_state = 15},
  [65] = {.lex_state = 15},
  [66] = {.lex_state = 15},
  [67] = {.lex_state = 15},
  [68] = {.lex_state = 1},
  [69] = {.lex_state = 15},
  [70] = {.lex_state = 15},
  [71] = {.lex_state = 1},
  [72] = {.lex_state = 15},
  [73] = {.lex_state = 1},
  [74] = {.lex_state = 15},
  [75] = {.lex_state = 15},
  [76] = {.lex_state = 1},
  [77] = {.lex_state = 1},
  [78] = {.lex_state = 15},
  [79] = {.lex_state = 15},
  [80] = {.lex_state = 15},
  [81] = {.lex_state = 15},
  [82] = {.lex_state = 15},
  [83] = {.lex_state = 1},
  [84] = {.lex_state = 15},
  [85] = {.lex_state = 15},
  [86] = {.lex_state = 15},
  [87] = {.lex_state = 1},
  [88] = {.lex_state = 1},
  [89] = {.lex_state = 1},
  [90] = {.lex_state = 1},
  [91] = {.lex_state = 15},
  [92] = {.lex_state = 15},
  [93] = {.lex_state = 15},
  [94] = {.lex_state = 15},
  [95] = {.lex_state = 15},
  [96] = {.lex_state = 1},
  [97] = {.lex_state = 15},
  [98] = {.lex_state = 1},
  [99] = {.lex_state = 1},
  [100] = {.lex_state = 15},
  [101] = {.lex_state = 15},
  [102] = {.lex_state = 15},
  [103] = {.lex_state = 15},
  [104] = {.lex_state = 15},
  [105] = {.lex_state = 15},
  [106] = {.lex_state = 15},
  [107] = {.lex_state = 15},
  [108] = {.lex_state = 15},
  [109] = {.lex_state = 15},
  [110] = {.lex_state = 1},
  [111] = {.lex_state = 1},
  [112] = {.lex_state = 15},
  [113] = {.lex_state = 15},
  [114] = {.lex_state = 1},
  [115] = {.lex_state = 1},
  [116] = {.lex_state = 15},
  [117] = {.lex_state = 1},
  [118] = {.lex_state = 1},
  [119] = {.lex_state = 15},
  [120] = {.lex_state = 15},
  [121] = {.lex_state = 1},
  [122] = {.lex_state = 11},
  [123] = {.lex_state = 15},
  [124] = {.lex_state = 15},
  [125] = {.lex_state = 1},
  [126] = {.lex_state = 9},
  [127] = {.lex_state = 15},
  [128] = {.lex_state = 15},
  [129] = {.lex_state = 0},
  [130] = {.lex_state = 15},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
    [sym__ws] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACE_PERCENT] = ACTIONS(1),
    [anon_sym_join] = ACTIONS(1),
    [anon_sym_in] = ACTIONS(1),
    [anon_sym_with] = ACTIONS(1),
    [anon_sym_endjoin] = ACTIONS(1),
    [anon_sym_for] = ACTIONS(1),
    [anon_sym_endfor] = ACTIONS(1),
  },
  [1] = {
    [sym_source_file] = STATE(129),
    [sym__statement] = STATE(2),
    [sym_expression_statement] = STATE(2),
    [sym_join_statement] = STATE(2),
    [sym_for_in_statement] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(5),
    [anon_sym_LBRACE_PERCENT] = ACTIONS(7),
    [sym_text_statement] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(5), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(7), 1,
      anon_sym_LBRACE_PERCENT,
    ACTIONS(11), 1,
      ts_builtin_sym_end,
    ACTIONS(13), 1,
      sym_text_statement,
    STATE(3), 5,
      sym__statement,
      sym_expression_statement,
      sym_join_statement,
      sym_for_in_statement,
      aux_sym_source_file_repeat1,
  [20] = 5,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    ACTIONS(17), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(20), 1,
      anon_sym_LBRACE_PERCENT,
    ACTIONS(23), 1,
      sym_text_statement,
    STATE(3), 5,
      sym__statement,
      sym_expression_statement,
      sym_join_statement,
      sym_for_in_statement,
      aux_sym_source_file_repeat1,
  [40] = 4,
    ACTIONS(26), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(28), 1,
      anon_sym_LBRACE_PERCENT,
    ACTIONS(30), 1,
      sym_text_statement,
    STATE(13), 5,
      sym__statement,
      sym_expression_statement,
      sym_join_statement,
      sym_for_in_statement,
      aux_sym_source_file_repeat1,
  [57] = 6,
    ACTIONS(32), 1,
      sym_identifier,
    ACTIONS(34), 1,
      anon_sym_DQUOTE,
    ACTIONS(36), 1,
      anon_sym_SQUOTE,
    ACTIONS(38), 1,
      sym_integer,
    STATE(60), 1,
      sym_string,
    STATE(83), 3,
      sym_reference_expression,
      sym_literal_expression,
      sym__expression,
  [78] = 6,
    ACTIONS(32), 1,
      sym_identifier,
    ACTIONS(34), 1,
      anon_sym_DQUOTE,
    ACTIONS(36), 1,
      anon_sym_SQUOTE,
    ACTIONS(38), 1,
      sym_integer,
    STATE(60), 1,
      sym_string,
    STATE(80), 3,
      sym_reference_expression,
      sym_literal_expression,
      sym__expression,
  [99] = 6,
    ACTIONS(32), 1,
      sym_identifier,
    ACTIONS(34), 1,
      anon_sym_DQUOTE,
    ACTIONS(36), 1,
      anon_sym_SQUOTE,
    ACTIONS(38), 1,
      sym_integer,
    STATE(60), 1,
      sym_string,
    STATE(119), 3,
      sym_reference_expression,
      sym_literal_expression,
      sym__expression,
  [120] = 6,
    ACTIONS(32), 1,
      sym_identifier,
    ACTIONS(34), 1,
      anon_sym_DQUOTE,
    ACTIONS(36), 1,
      anon_sym_SQUOTE,
    ACTIONS(38), 1,
      sym_integer,
    STATE(60), 1,
      sym_string,
    STATE(121), 3,
      sym_reference_expression,
      sym_literal_expression,
      sym__expression,
  [141] = 4,
    ACTIONS(26), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(40), 1,
      anon_sym_LBRACE_PERCENT,
    ACTIONS(42), 1,
      sym_text_statement,
    STATE(20), 5,
      sym__statement,
      sym_expression_statement,
      sym_join_statement,
      sym_for_in_statement,
      aux_sym_source_file_repeat1,
  [158] = 6,
    ACTIONS(32), 1,
      sym_identifier,
    ACTIONS(34), 1,
      anon_sym_DQUOTE,
    ACTIONS(36), 1,
      anon_sym_SQUOTE,
    ACTIONS(38), 1,
      sym_integer,
    STATE(60), 1,
      sym_string,
    STATE(113), 3,
      sym_reference_expression,
      sym_literal_expression,
      sym__expression,
  [179] = 6,
    ACTIONS(32), 1,
      sym_identifier,
    ACTIONS(34), 1,
      anon_sym_DQUOTE,
    ACTIONS(36), 1,
      anon_sym_SQUOTE,
    ACTIONS(38), 1,
      sym_integer,
    STATE(60), 1,
      sym_string,
    STATE(75), 3,
      sym_reference_expression,
      sym_literal_expression,
      sym__expression,
  [200] = 6,
    ACTIONS(32), 1,
      sym_identifier,
    ACTIONS(34), 1,
      anon_sym_DQUOTE,
    ACTIONS(36), 1,
      anon_sym_SQUOTE,
    ACTIONS(38), 1,
      sym_integer,
    STATE(60), 1,
      sym_string,
    STATE(112), 3,
      sym_reference_expression,
      sym_literal_expression,
      sym__expression,
  [221] = 4,
    ACTIONS(26), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(42), 1,
      sym_text_statement,
    ACTIONS(44), 1,
      anon_sym_LBRACE_PERCENT,
    STATE(20), 5,
      sym__statement,
      sym_expression_statement,
      sym_join_statement,
      sym_for_in_statement,
      aux_sym_source_file_repeat1,
  [238] = 4,
    ACTIONS(26), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(46), 1,
      anon_sym_LBRACE_PERCENT,
    ACTIONS(48), 1,
      sym_text_statement,
    STATE(19), 5,
      sym__statement,
      sym_expression_statement,
      sym_join_statement,
      sym_for_in_statement,
      aux_sym_source_file_repeat1,
  [255] = 6,
    ACTIONS(32), 1,
      sym_identifier,
    ACTIONS(34), 1,
      anon_sym_DQUOTE,
    ACTIONS(36), 1,
      anon_sym_SQUOTE,
    ACTIONS(38), 1,
      sym_integer,
    STATE(60), 1,
      sym_string,
    STATE(79), 3,
      sym_reference_expression,
      sym_literal_expression,
      sym__expression,
  [276] = 4,
    ACTIONS(26), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(42), 1,
      sym_text_statement,
    ACTIONS(50), 1,
      anon_sym_LBRACE_PERCENT,
    STATE(20), 5,
      sym__statement,
      sym_expression_statement,
      sym_join_statement,
      sym_for_in_statement,
      aux_sym_source_file_repeat1,
  [293] = 4,
    ACTIONS(26), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(52), 1,
      anon_sym_LBRACE_PERCENT,
    ACTIONS(54), 1,
      sym_text_statement,
    STATE(9), 5,
      sym__statement,
      sym_expression_statement,
      sym_join_statement,
      sym_for_in_statement,
      aux_sym_source_file_repeat1,
  [310] = 4,
    ACTIONS(26), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(56), 1,
      anon_sym_LBRACE_PERCENT,
    ACTIONS(58), 1,
      sym_text_statement,
    STATE(16), 5,
      sym__statement,
      sym_expression_statement,
      sym_join_statement,
      sym_for_in_statement,
      aux_sym_source_file_repeat1,
  [327] = 4,
    ACTIONS(26), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(42), 1,
      sym_text_statement,
    ACTIONS(60), 1,
      anon_sym_LBRACE_PERCENT,
    STATE(20), 5,
      sym__statement,
      sym_expression_statement,
      sym_join_statement,
      sym_for_in_statement,
      aux_sym_source_file_repeat1,
  [344] = 4,
    ACTIONS(62), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(65), 1,
      anon_sym_LBRACE_PERCENT,
    ACTIONS(68), 1,
      sym_text_statement,
    STATE(20), 5,
      sym__statement,
      sym_expression_statement,
      sym_join_statement,
      sym_for_in_statement,
      aux_sym_source_file_repeat1,
  [361] = 4,
    ACTIONS(71), 1,
      sym_identifier,
    ACTIONS(73), 1,
      anon_sym_LPAREN,
    ACTIONS(75), 1,
      anon_sym_RPAREN,
    STATE(93), 3,
      sym__pattern,
      sym_var_pattern,
      sym_tuple_pattern,
  [376] = 4,
    ACTIONS(71), 1,
      sym_identifier,
    ACTIONS(73), 1,
      anon_sym_LPAREN,
    ACTIONS(77), 1,
      anon_sym_RPAREN,
    STATE(86), 3,
      sym__pattern,
      sym_var_pattern,
      sym_tuple_pattern,
  [391] = 3,
    ACTIONS(71), 1,
      sym_identifier,
    ACTIONS(73), 1,
      anon_sym_LPAREN,
    STATE(127), 3,
      sym__pattern,
      sym_var_pattern,
      sym_tuple_pattern,
  [403] = 3,
    ACTIONS(71), 1,
      sym_identifier,
    ACTIONS(73), 1,
      anon_sym_LPAREN,
    STATE(100), 3,
      sym__pattern,
      sym_var_pattern,
      sym_tuple_pattern,
  [415] = 3,
    ACTIONS(71), 1,
      sym_identifier,
    ACTIONS(73), 1,
      anon_sym_LPAREN,
    STATE(101), 3,
      sym__pattern,
      sym_var_pattern,
      sym_tuple_pattern,
  [427] = 3,
    ACTIONS(71), 1,
      sym_identifier,
    ACTIONS(73), 1,
      anon_sym_LPAREN,
    STATE(120), 3,
      sym__pattern,
      sym_var_pattern,
      sym_tuple_pattern,
  [439] = 3,
    ACTIONS(79), 1,
      sym_identifier,
    ACTIONS(81), 1,
      anon_sym_LPAREN,
    STATE(51), 3,
      sym__pattern,
      sym_var_pattern,
      sym_tuple_pattern,
  [451] = 2,
    ACTIONS(85), 1,
      sym_text_statement,
    ACTIONS(83), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
  [460] = 2,
    ACTIONS(89), 1,
      sym_text_statement,
    ACTIONS(87), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
  [469] = 2,
    ACTIONS(93), 1,
      sym_text_statement,
    ACTIONS(91), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
  [478] = 2,
    ACTIONS(97), 1,
      sym_text_statement,
    ACTIONS(95), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
  [487] = 2,
    ACTIONS(101), 1,
      sym_text_statement,
    ACTIONS(99), 3,
      ts_builtin_sym_end,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
  [496] = 3,
    ACTIONS(103), 1,
      anon_sym_COMMA,
    ACTIONS(105), 1,
      anon_sym_RPAREN,
    STATE(49), 1,
      aux_sym_tuple_pattern_repeat1,
  [506] = 3,
    ACTIONS(107), 1,
      anon_sym_join,
    ACTIONS(109), 1,
      anon_sym_for,
    ACTIONS(111), 1,
      anon_sym_endfor,
  [516] = 2,
    ACTIONS(85), 1,
      sym_text_statement,
    ACTIONS(83), 2,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
  [524] = 2,
    ACTIONS(101), 1,
      sym_text_statement,
    ACTIONS(99), 2,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
  [532] = 3,
    ACTIONS(103), 1,
      anon_sym_COMMA,
    ACTIONS(113), 1,
      anon_sym_RPAREN,
    STATE(42), 1,
      aux_sym_tuple_pattern_repeat1,
  [542] = 2,
    ACTIONS(97), 1,
      sym_text_statement,
    ACTIONS(95), 2,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
  [550] = 3,
    ACTIONS(107), 1,
      anon_sym_join,
    ACTIONS(109), 1,
      anon_sym_for,
    ACTIONS(115), 1,
      anon_sym_endjoin,
  [560] = 3,
    ACTIONS(107), 1,
      anon_sym_join,
    ACTIONS(109), 1,
      anon_sym_for,
    ACTIONS(117), 1,
      anon_sym_endfor,
  [570] = 3,
    ACTIONS(107), 1,
      anon_sym_join,
    ACTIONS(109), 1,
      anon_sym_for,
    ACTIONS(119), 1,
      anon_sym_endjoin,
  [580] = 3,
    ACTIONS(121), 1,
      anon_sym_COMMA,
    ACTIONS(124), 1,
      anon_sym_RPAREN,
    STATE(42), 1,
      aux_sym_tuple_pattern_repeat1,
  [590] = 3,
    ACTIONS(107), 1,
      anon_sym_join,
    ACTIONS(109), 1,
      anon_sym_for,
    ACTIONS(126), 1,
      anon_sym_endjoin,
  [600] = 3,
    ACTIONS(103), 1,
      anon_sym_COMMA,
    ACTIONS(128), 1,
      anon_sym_RPAREN,
    STATE(37), 1,
      aux_sym_tuple_pattern_repeat1,
  [610] = 3,
    ACTIONS(107), 1,
      anon_sym_join,
    ACTIONS(109), 1,
      anon_sym_for,
    ACTIONS(130), 1,
      anon_sym_endfor,
  [620] = 2,
    ACTIONS(89), 1,
      sym_text_statement,
    ACTIONS(87), 2,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
  [628] = 3,
    ACTIONS(107), 1,
      anon_sym_join,
    ACTIONS(109), 1,
      anon_sym_for,
    ACTIONS(132), 1,
      anon_sym_endjoin,
  [638] = 2,
    ACTIONS(93), 1,
      sym_text_statement,
    ACTIONS(91), 2,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
  [646] = 3,
    ACTIONS(103), 1,
      anon_sym_COMMA,
    ACTIONS(134), 1,
      anon_sym_RPAREN,
    STATE(42), 1,
      aux_sym_tuple_pattern_repeat1,
  [656] = 3,
    ACTIONS(107), 1,
      anon_sym_join,
    ACTIONS(109), 1,
      anon_sym_for,
    ACTIONS(136), 1,
      anon_sym_endfor,
  [666] = 1,
    ACTIONS(138), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [671] = 1,
    ACTIONS(140), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [676] = 1,
    ACTIONS(142), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [681] = 1,
    ACTIONS(144), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [686] = 2,
    ACTIONS(146), 1,
      sym__ws,
    ACTIONS(148), 1,
      anon_sym_RBRACE_RBRACE,
  [693] = 2,
    ACTIONS(107), 1,
      anon_sym_join,
    ACTIONS(109), 1,
      anon_sym_for,
  [700] = 1,
    ACTIONS(150), 2,
      anon_sym_COMMA,
      anon_sym_RPAREN,
  [705] = 2,
    ACTIONS(152), 1,
      anon_sym_join,
    ACTIONS(154), 1,
      anon_sym_for,
  [712] = 2,
    ACTIONS(156), 1,
      sym__ws,
    ACTIONS(158), 1,
      anon_sym_RBRACE_RBRACE,
  [719] = 2,
    ACTIONS(160), 1,
      sym__ws,
    ACTIONS(162), 1,
      anon_sym_RBRACE_RBRACE,
  [726] = 1,
    ACTIONS(164), 1,
      anon_sym_PERCENT_RBRACE,
  [730] = 1,
    ACTIONS(166), 1,
      sym__ws,
  [734] = 1,
    ACTIONS(168), 1,
      sym__ws,
  [738] = 1,
    ACTIONS(170), 1,
      sym__ws,
  [742] = 1,
    ACTIONS(172), 1,
      sym__ws,
  [746] = 1,
    ACTIONS(174), 1,
      sym__ws,
  [750] = 1,
    ACTIONS(176), 1,
      sym__ws,
  [754] = 1,
    ACTIONS(178), 1,
      anon_sym_PERCENT_RBRACE,
  [758] = 1,
    ACTIONS(180), 1,
      sym__ws,
  [762] = 1,
    ACTIONS(182), 1,
      sym__ws,
  [766] = 1,
    ACTIONS(184), 1,
      anon_sym_PERCENT_RBRACE,
  [770] = 1,
    ACTIONS(186), 1,
      sym__ws,
  [774] = 1,
    ACTIONS(188), 1,
      anon_sym_PERCENT_RBRACE,
  [778] = 1,
    ACTIONS(190), 1,
      sym__ws,
  [782] = 1,
    ACTIONS(192), 1,
      sym__ws,
  [786] = 1,
    ACTIONS(194), 1,
      anon_sym_PERCENT_RBRACE,
  [790] = 1,
    ACTIONS(196), 1,
      anon_sym_with,
  [794] = 1,
    ACTIONS(150), 1,
      sym__ws,
  [798] = 1,
    ACTIONS(198), 1,
      sym__ws,
  [802] = 1,
    ACTIONS(200), 1,
      sym__ws,
  [806] = 1,
    ACTIONS(144), 1,
      sym__ws,
  [810] = 1,
    ACTIONS(202), 1,
      sym__ws,
  [814] = 1,
    ACTIONS(204), 1,
      anon_sym_RBRACE_RBRACE,
  [818] = 1,
    ACTIONS(206), 1,
      sym__ws,
  [822] = 1,
    ACTIONS(208), 1,
      sym__ws,
  [826] = 1,
    ACTIONS(210), 1,
      sym__ws,
  [830] = 1,
    ACTIONS(212), 1,
      anon_sym_PERCENT_RBRACE,
  [834] = 1,
    ACTIONS(214), 1,
      anon_sym_PERCENT_RBRACE,
  [838] = 1,
    ACTIONS(216), 1,
      anon_sym_PERCENT_RBRACE,
  [842] = 1,
    ACTIONS(218), 1,
      anon_sym_PERCENT_RBRACE,
  [846] = 1,
    ACTIONS(142), 1,
      sym__ws,
  [850] = 1,
    ACTIONS(220), 1,
      sym__ws,
  [854] = 1,
    ACTIONS(222), 1,
      sym__ws,
  [858] = 1,
    ACTIONS(224), 1,
      sym__ws,
  [862] = 1,
    ACTIONS(226), 1,
      sym__ws,
  [866] = 1,
    ACTIONS(228), 1,
      anon_sym_PERCENT_RBRACE,
  [870] = 1,
    ACTIONS(230), 1,
      sym__ws,
  [874] = 1,
    ACTIONS(232), 1,
      anon_sym_in,
  [878] = 1,
    ACTIONS(234), 1,
      anon_sym_in,
  [882] = 1,
    ACTIONS(236), 1,
      sym__ws,
  [886] = 1,
    ACTIONS(238), 1,
      sym__ws,
  [890] = 1,
    ACTIONS(240), 1,
      sym__ws,
  [894] = 1,
    ACTIONS(242), 1,
      sym__ws,
  [898] = 1,
    ACTIONS(244), 1,
      sym__ws,
  [902] = 1,
    ACTIONS(246), 1,
      sym__ws,
  [906] = 1,
    ACTIONS(248), 1,
      sym__ws,
  [910] = 1,
    ACTIONS(140), 1,
      sym__ws,
  [914] = 1,
    ACTIONS(250), 1,
      sym__ws,
  [918] = 1,
    ACTIONS(252), 1,
      sym__ws,
  [922] = 1,
    ACTIONS(254), 1,
      anon_sym_PERCENT_RBRACE,
  [926] = 1,
    ACTIONS(256), 1,
      anon_sym_PERCENT_RBRACE,
  [930] = 1,
    ACTIONS(258), 1,
      sym__ws,
  [934] = 1,
    ACTIONS(260), 1,
      sym__ws,
  [938] = 1,
    ACTIONS(262), 1,
      anon_sym_SQUOTE,
  [942] = 1,
    ACTIONS(262), 1,
      anon_sym_DQUOTE,
  [946] = 1,
    ACTIONS(264), 1,
      sym__ws,
  [950] = 1,
    ACTIONS(266), 1,
      anon_sym_with,
  [954] = 1,
    ACTIONS(268), 1,
      anon_sym_in,
  [958] = 1,
    ACTIONS(270), 1,
      sym__ws,
  [962] = 1,
    ACTIONS(272), 1,
      sym__ws,
  [966] = 1,
    ACTIONS(274), 1,
      anon_sym_RBRACE_RBRACE,
  [970] = 1,
    ACTIONS(276), 1,
      aux_sym_string_token2,
  [974] = 1,
    ACTIONS(278), 1,
      sym__ws,
  [978] = 1,
    ACTIONS(280), 1,
      sym__ws,
  [982] = 1,
    ACTIONS(282), 1,
      anon_sym_in,
  [986] = 1,
    ACTIONS(284), 1,
      aux_sym_string_token1,
  [990] = 1,
    ACTIONS(286), 1,
      sym__ws,
  [994] = 1,
    ACTIONS(288), 1,
      sym__ws,
  [998] = 1,
    ACTIONS(290), 1,
      ts_builtin_sym_end,
  [1002] = 1,
    ACTIONS(292), 1,
      sym__ws,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 20,
  [SMALL_STATE(4)] = 40,
  [SMALL_STATE(5)] = 57,
  [SMALL_STATE(6)] = 78,
  [SMALL_STATE(7)] = 99,
  [SMALL_STATE(8)] = 120,
  [SMALL_STATE(9)] = 141,
  [SMALL_STATE(10)] = 158,
  [SMALL_STATE(11)] = 179,
  [SMALL_STATE(12)] = 200,
  [SMALL_STATE(13)] = 221,
  [SMALL_STATE(14)] = 238,
  [SMALL_STATE(15)] = 255,
  [SMALL_STATE(16)] = 276,
  [SMALL_STATE(17)] = 293,
  [SMALL_STATE(18)] = 310,
  [SMALL_STATE(19)] = 327,
  [SMALL_STATE(20)] = 344,
  [SMALL_STATE(21)] = 361,
  [SMALL_STATE(22)] = 376,
  [SMALL_STATE(23)] = 391,
  [SMALL_STATE(24)] = 403,
  [SMALL_STATE(25)] = 415,
  [SMALL_STATE(26)] = 427,
  [SMALL_STATE(27)] = 439,
  [SMALL_STATE(28)] = 451,
  [SMALL_STATE(29)] = 460,
  [SMALL_STATE(30)] = 469,
  [SMALL_STATE(31)] = 478,
  [SMALL_STATE(32)] = 487,
  [SMALL_STATE(33)] = 496,
  [SMALL_STATE(34)] = 506,
  [SMALL_STATE(35)] = 516,
  [SMALL_STATE(36)] = 524,
  [SMALL_STATE(37)] = 532,
  [SMALL_STATE(38)] = 542,
  [SMALL_STATE(39)] = 550,
  [SMALL_STATE(40)] = 560,
  [SMALL_STATE(41)] = 570,
  [SMALL_STATE(42)] = 580,
  [SMALL_STATE(43)] = 590,
  [SMALL_STATE(44)] = 600,
  [SMALL_STATE(45)] = 610,
  [SMALL_STATE(46)] = 620,
  [SMALL_STATE(47)] = 628,
  [SMALL_STATE(48)] = 638,
  [SMALL_STATE(49)] = 646,
  [SMALL_STATE(50)] = 656,
  [SMALL_STATE(51)] = 666,
  [SMALL_STATE(52)] = 671,
  [SMALL_STATE(53)] = 676,
  [SMALL_STATE(54)] = 681,
  [SMALL_STATE(55)] = 686,
  [SMALL_STATE(56)] = 693,
  [SMALL_STATE(57)] = 700,
  [SMALL_STATE(58)] = 705,
  [SMALL_STATE(59)] = 712,
  [SMALL_STATE(60)] = 719,
  [SMALL_STATE(61)] = 726,
  [SMALL_STATE(62)] = 730,
  [SMALL_STATE(63)] = 734,
  [SMALL_STATE(64)] = 738,
  [SMALL_STATE(65)] = 742,
  [SMALL_STATE(66)] = 746,
  [SMALL_STATE(67)] = 750,
  [SMALL_STATE(68)] = 754,
  [SMALL_STATE(69)] = 758,
  [SMALL_STATE(70)] = 762,
  [SMALL_STATE(71)] = 766,
  [SMALL_STATE(72)] = 770,
  [SMALL_STATE(73)] = 774,
  [SMALL_STATE(74)] = 778,
  [SMALL_STATE(75)] = 782,
  [SMALL_STATE(76)] = 786,
  [SMALL_STATE(77)] = 790,
  [SMALL_STATE(78)] = 794,
  [SMALL_STATE(79)] = 798,
  [SMALL_STATE(80)] = 802,
  [SMALL_STATE(81)] = 806,
  [SMALL_STATE(82)] = 810,
  [SMALL_STATE(83)] = 814,
  [SMALL_STATE(84)] = 818,
  [SMALL_STATE(85)] = 822,
  [SMALL_STATE(86)] = 826,
  [SMALL_STATE(87)] = 830,
  [SMALL_STATE(88)] = 834,
  [SMALL_STATE(89)] = 838,
  [SMALL_STATE(90)] = 842,
  [SMALL_STATE(91)] = 846,
  [SMALL_STATE(92)] = 850,
  [SMALL_STATE(93)] = 854,
  [SMALL_STATE(94)] = 858,
  [SMALL_STATE(95)] = 862,
  [SMALL_STATE(96)] = 866,
  [SMALL_STATE(97)] = 870,
  [SMALL_STATE(98)] = 874,
  [SMALL_STATE(99)] = 878,
  [SMALL_STATE(100)] = 882,
  [SMALL_STATE(101)] = 886,
  [SMALL_STATE(102)] = 890,
  [SMALL_STATE(103)] = 894,
  [SMALL_STATE(104)] = 898,
  [SMALL_STATE(105)] = 902,
  [SMALL_STATE(106)] = 906,
  [SMALL_STATE(107)] = 910,
  [SMALL_STATE(108)] = 914,
  [SMALL_STATE(109)] = 918,
  [SMALL_STATE(110)] = 922,
  [SMALL_STATE(111)] = 926,
  [SMALL_STATE(112)] = 930,
  [SMALL_STATE(113)] = 934,
  [SMALL_STATE(114)] = 938,
  [SMALL_STATE(115)] = 942,
  [SMALL_STATE(116)] = 946,
  [SMALL_STATE(117)] = 950,
  [SMALL_STATE(118)] = 954,
  [SMALL_STATE(119)] = 958,
  [SMALL_STATE(120)] = 962,
  [SMALL_STATE(121)] = 966,
  [SMALL_STATE(122)] = 970,
  [SMALL_STATE(123)] = 974,
  [SMALL_STATE(124)] = 978,
  [SMALL_STATE(125)] = 982,
  [SMALL_STATE(126)] = 986,
  [SMALL_STATE(127)] = 990,
  [SMALL_STATE(128)] = 994,
  [SMALL_STATE(129)] = 998,
  [SMALL_STATE(130)] = 1002,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [17] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(8),
  [20] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(66),
  [23] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(3),
  [26] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [28] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [30] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [32] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [34] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [36] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [38] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [40] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [42] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [44] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [48] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [54] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [58] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [62] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(5),
  [65] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(128),
  [68] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(20),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [75] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_join_statement, 19),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_join_statement, 19),
  [87] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_join_statement, 20),
  [89] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_join_statement, 20),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression_statement, 3),
  [93] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression_statement, 3),
  [95] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_for_in_statement, 16),
  [97] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_for_in_statement, 16),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_for_in_statement, 17),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_for_in_statement, 17),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [121] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_tuple_pattern_repeat1, 2), SHIFT_REPEAT(82),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tuple_pattern_repeat1, 2),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [130] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [132] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [138] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_tuple_pattern_repeat1, 3),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_var_pattern, 1),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple_pattern, 3),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple_pattern, 5),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tuple_pattern, 6),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [156] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_reference_expression, 1),
  [158] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_reference_expression, 1),
  [160] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_literal_expression, 1),
  [162] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal_expression, 1),
  [164] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [166] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [168] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [172] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [174] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [178] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [180] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [182] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [184] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [186] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [192] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [198] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [200] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [204] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [222] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [238] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [240] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [242] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [244] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [246] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [248] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [250] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [254] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [256] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [258] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [260] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [262] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [264] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(116),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [272] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [274] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [280] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(123),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(125),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [290] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_templaty(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
